### ISSUE TITLE
Native build problems

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-cli#130]
While graalvm has been on a backburner lately, this issue track work to bring it back.

**Comment by jvalkeal** [comment]
Missing `helpers.nashorn.js`

```
Caused by: java.lang.ExceptionInInitializerError: null
	at com.github.jknack.handlebars.Handlebars.<init>(Handlebars.java:276) ~[spring:na]
	at com.github.jknack.handlebars.Handlebars.<init>(Handlebars.java:374) ~[spring:na]
	at org.springframework.cli.runtime.engine.templating.HandlebarsTemplateEngine.<init>(HandlebarsTemplateEngine.java:39) ~[na:na]
	at org.springframework.cli.merger.ai.service.AbstractOpenAiService.<init>(AbstractOpenAiService.java:46) ~[spring:na]
	at org.springframework.cli.merger.ai.service.GenerateCodeAiService.<init>(GenerateCodeAiService.java:35) ~[na:na]
	at org.springframework.cli.command.AiCommands.<init>(AiCommands.java:47) ~[spring:na]
```
